### ISSUE TITLE
add MS Band error notification--> text

### ISSUE THREAD

**Issue by cmgordon** [ctpc/nucoach-issues#46]
@imana97 Android
@Navarjun iOS

**Comment by imana97** [comment]
**PLEASE DO NOT TAKE ACTION UNTIL FURTHER NOTICE!**

The purpose of this thread is to add notification to deephealth collector apps so that they send notification to the user when the band is disconnected.
see here for notification:
https://nucoach.org/console/#!/build/api-docs#anchorHC_notification

simply send:
TITLE, BODY,USER. other fields are not needed.

for the title put:

Title: "MS band Disconnect"
Body: "MS band was disconnected, please try to reconnect... "
